/* Generated by build-map-data.py — do not hand-edit. */
const MAP_SNAPSHOT = "2026-09-30";
const COUNTRIES = [
  {
    "name": "Germany",
    "lat": 52.51604,
    "lng": 13.37691,
    "scenes": 383,
    "url": "https://devlij.github.io/jason-ds-vision-germany/",
    "src": "local germany-pages/data.json (383 entries)"
  },
  {
    "name": "Norway",
    "lat": 59.91234,
    "lng": 10.75,
    "scenes": 552,
    "url": "https://devlij.github.io/jason-ds-vision-norway-preview/",
    "src": "local norway-pages/data.json (552 entries)"
  },
  {
    "name": "Finland",
    "lat": 60.17116,
    "lng": 24.93265,
    "scenes": 233,
    "url": "https://devlij.github.io/jason-ds-vision-finland-preview/",
    "src": "local library/finland masters (233 scenes)"
  },
  {
    "name": "France",
    "lat": 48.85717,
    "lng": 2.3414,
    "scenes": 365,
    "url": "https://devlij.github.io/jason-ds-vision-france-preview/",
    "src": "devlij/jason-ds-vision-france-preview index.html id-regex FR-01-\\d{3} (365)"
  },
  {
    "name": "Italy",
    "lat": 41.90325,
    "lng": 12.49563,
    "scenes": 375,
    "url": "https://devlij.github.io/jason-ds-vision-italy-preview/",
    "src": "devlij/jason-ds-vision-italy-preview index.html id-regex IT-01-\\d{3} (375)"
  },
  {
    "name": "Spain",
    "lat": 40.42024,
    "lng": -3.68756,
    "scenes": 365,
    "url": "https://devlij.github.io/jason-ds-vision-spain-preview/",
    "src": "devlij/jason-ds-vision-spain-preview index.html id-regex ES-01-\\d{3} (365)"
  },
  {
    "name": "Greece",
    "lat": 37.97614,
    "lng": 23.7364,
    "scenes": 365,
    "url": "https://devlij.github.io/jason-ds-vision-greece-preview/",
    "src": "devlij/jason-ds-vision-greece-preview index.html id-regex GR-01-\\d{3} (365)"
  },
  {
    "name": "Denmark",
    "lat": 55.67567,
    "lng": 12.56755,
    "scenes": 365,
    "url": "https://devlij.github.io/jason-ds-vision-denmark-preview/",
    "src": "devlij/jason-ds-vision-denmark-preview index.html id-regex DK-01-\\d{3} (365)"
  },
  {
    "name": "Netherlands",
    "lat": 52.36993,
    "lng": 4.90787,
    "scenes": 288,
    "url": "https://devlij.github.io/jason-ds-vision-netherlands-preview/",
    "src": "devlij/jason-ds-vision-netherlands-preview index.html id-regex NL-01-\\d{3} (288)"
  },
  {
    "name": "Sweden",
    "lat": 59.33257,
    "lng": 18.06682,
    "scenes": 91,
    "url": "https://devlij.github.io/jason-ds-vision-sweden-preview/",
    "src": "devlij/jason-ds-vision-sweden-preview index.html id-regex SE-01-\\d{3} (91)"
  }
];
